# Generated by Django 5.2 on 2025-04-09 05:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_events_options_rsos_members_alter_rsos_admin_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='lname',
            field=models.ForeignKey(blank=True, db_column='lname', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='accounts.locations'),
        ),
    ]
