# Generated by Django 5.2 on 2025-04-09 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_events_lname'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventcreation',
            name='admin',
        ),
        migrations.RemoveField(
            model_name='eventcreation',
            name='event',
        ),
        migrations.RemoveField(
            model_name='eventcreation',
            name='superadmin',
        ),
        migrations.AlterUniqueTogether(
            name='events',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='events',
            name='lname',
        ),
        migrations.RemoveField(
            model_name='events',
            name='university',
        ),
        migrations.RemoveField(
            model_name='rsoevents',
            name='event',
        ),
        migrations.RemoveField(
            model_name='rsoevents',
            name='rso',
        ),
        migrations.RemoveField(
            model_name='rsos',
            name='admin',
        ),
        migrations.RemoveField(
            model_name='rsos',
            name='members',
        ),
        migrations.RemoveField(
            model_name='rsos',
            name='university',
        ),
        migrations.RemoveField(
            model_name='studentsrsos',
            name='rso',
        ),
        migrations.AlterUniqueTogether(
            name='studentsrsos',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='studentsrsos',
            name='uid',
        ),
        migrations.DeleteModel(
            name='Comments',
        ),
        migrations.DeleteModel(
            name='EventCreation',
        ),
        migrations.DeleteModel(
            name='Locations',
        ),
        migrations.DeleteModel(
            name='Events',
        ),
        migrations.DeleteModel(
            name='RSOEvents',
        ),
        migrations.DeleteModel(
            name='Universities',
        ),
        migrations.DeleteModel(
            name='RSOs',
        ),
        migrations.DeleteModel(
            name='StudentsRSOs',
        ),
    ]
